AWSTemplateFormatVersion: 2010-09-09

Description: WordPress Project

Mappings: 
  RegionMap: 
    us-east-1: 
      'AmazonLinux2': ami-0cebb45b34604efb8 
      'AmazonLinux': ami-00514a528eadbc95b 
Metadata:

    Authors:
        Description:  Fernando Brambilla de Mello
    
    AWS::CloudFormation::Interface:
      ParameterGroups:
      - Label:
          default: Network
        Parameters:
            - VpcName
            - VpcCIDR
            - PublicSubnet1CIDR
            - PublicSubnet2CIDR
            - PrivateSubnet1CIDR
            - PrivateSubnet2CIDR
            - SshCidrAllow
      - Label:
          default: EC2 Instance
        Parameters:
            - InstanceName
            - InstanceType
            - KeyName
            - AmiType
      - Label:
          default: RDS Instance
        Parameters:
            - DBInstanceId
            - DBName
            - MasterUsername
            - MasterUserPassword
            - Engine
            - DBInstanceClass
            - AllocatedStorage
  
      ParameterLabels:
        VpcName:
          default: VPC name
        VpcCIDR:
          default: VpcCidr
        PublicSubnet1CIDR:
          default: Public Subnet 1
        PublicSubnet2CIDR:
          default: Public Subnet 2
        PrivateSubnet1CIDR:
          default: Private Subnet 1
        PrivateSubnet2CIDR:
          default: Private Subnet 2
        SshCidrAllow:
          default: SSH CIDR 
        InstanceName:
          default: Instance name
        InstanceType:
          default: Instance Size
        KeyName:
          default: SSH access key
        AmiType:
          default: AMI type
        DBInstanceId:
          default: The RDS DB Instance Identifier
        DBName:
          default: The RDS DB Instance Name
        MasterUsername:
          default: The RDS DB Instance UserName
        MasterUserPassword:
          default: The RDS DB Instance Password
        Engine:
          default: The RDS DB Engine Type
        DBInstanceClass:
          default: The RDS DB Instance Type
        AllocatedStorage:
          default: The RDS DB Size in GB

Parameters:
  VpcName:
    Description: The VPN Name
    Type: String
    Default: WP-VPC

  VpcCIDR:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC
    Type: String

  PublicSubnet1CIDR:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: Please enter the IP range
    Type: String
    Default: 10.0.1.0/24

  PublicSubnet2CIDR:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: Please enter the IP range
    Type: String
    Default: 10.0.2.0/24

  PrivateSubnet1CIDR:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: Please enter the IP range
    Type: String
    Default: 10.0.5.0/24

  PrivateSubnet2CIDR:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: Please enter the IP range
    Type: String
    Default: 10.0.4.0/24

  SshCidrAllow:
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    Type: String
    Description: IP Address to allow ssh
    Default: 0.0.0.0/0

  InstanceName:
    Type: String
    Default: WebServer

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - m4.large
    - m3.medium
    - c4.large
    - c3.large

  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  AmiType:
    Description: what kind of AMI
    Type: String
    Default: AmazonLinux2 
    AllowedValues:
      - AmazonLinux2 
      - AmazonLinux

  DBInstanceId:
    Description: "The RDS DB Instance Identifier"
    Type: String
    Default: RDS-Instance
    ConstraintDescription: Must be a valid RDS instance ID

  DBName:
    Description: "The RDS DB Instance Name"
    Type: String
    Default: WPDB
    ConstraintDescription: No Special Characters

  MasterUsername:
    Description: The master user name for the DB instance.
    Type: String
    Default: MasterUser

  MasterUserPassword:
    Description: The master password for the DB instance.
    Type: String
    NoEcho: false
    Default: admin0000

  Engine:
    Description: The name of the database engine to be used for this instance.
    Type: String
    AllowedValues: [mysql, mariadb, postgres]
    ConstraintDescription: "Please specify either a mysql, mariadb, or postgres engine for the RDS instance."
    Default: mysql

  DBInstanceClass:
    Description: The name of the compute and memory capacity classes of the DB instance.
    Type: String
    Default: db.t2.micro
    AllowedValues:
      - db.t2.micro
      - db.t2.small
      
  AllocatedStorage:
    Description: The allocated storage size, specified in gigabytes (GB).
    Type: String
    ConstraintDescription: "Value must be a valid number between 10-16384."
    Default: 10

Resources: 
  StackVPC: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: "https://aws-cloudformation-wordpress.s3.amazonaws.com/Wp-VPC.yaml" 
      TimeoutInMinutes: '60'
      Parameters:
        VpcName: !Ref VpcName
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
        SshCidrAllow: !Ref SshCidrAllow

  StackSG: 
    Type: AWS::CloudFormation::Stack
    DependsOn: StackVPC 
    Properties: 
      TemplateURL: "https://aws-cloudformation-wordpress.s3.amazonaws.com/Wp-SecurityGroups.yaml" 
      TimeoutInMinutes: '60'
      Parameters:
        SshCidrAllow: !Ref SshCidrAllow
        myVpc: !GetAtt  StackVPC.Outputs.myVpc 
        Subnet3: !GetAtt  StackVPC.Outputs.Subnet3 
        Subnet4: !GetAtt  StackVPC.Outputs.Subnet4 
  
  StackRDS: 
    Type: AWS::CloudFormation::Stack
    DependsOn: StackSG 
    Properties: 
      TemplateURL: "https://aws-cloudformation-wordpress.s3.amazonaws.com/Wp-RDS.yaml" 
      TimeoutInMinutes: '60'
      Parameters:                   
        DBInstanceId: !Ref DBInstanceId
        DBName: !Ref DBName
        MasterUsername: !Ref MasterUsername
        MasterUserPassword: !Ref MasterUserPassword
        Engine: !Ref Engine
        DBInstanceClass: !Ref DBInstanceClass
        AllocatedStorage: !Ref AllocatedStorage    
        RDSSecurityGroup: !GetAtt  StackSG.Outputs.RDSSecurityGroup
        RDBSubnetGroup: !GetAtt  StackSG.Outputs.RDBSubnetGroup


  StackEC2: 
    Type: AWS::CloudFormation::Stack
    DependsOn: StackRDS 
    Properties: 
      TemplateURL: "https://aws-cloudformation-wordpress.s3.amazonaws.com/Wp-EC2.yaml" 
      TimeoutInMinutes: '60'
      Parameters:
        DBName: !Ref DBName
        MasterUsername: !Ref MasterUsername
        MasterUserPassword: !Ref MasterUserPassword
        InstanceName: !Ref InstanceName
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        AmiType: !Ref AmiType
        Subnet1: !GetAtt  StackVPC.Outputs.Subnet1 
        WebSecurityGroup: !GetAtt  StackSG.Outputs.WebSecurityGroup
        DBEndpoint:  !GetAtt  StackRDS.Outputs.DBEndpoint 

  # StackRoute53: 
  #   Type: AWS::CloudFormation::Stack
  #   DependsOn: StackEC2 
  #   Properties: 
  #     TemplateURL: "https://aws-cloudformation-wordpress.s3.amazonaws.com/Wp-Route53.yaml"  
  #     TimeoutInMinutes: '60'
  #     Parameters:
  #       ec2Ip:  !GetAtt  StackEC2.Outputs.ec2Ip 


 
