AWSTemplateFormatVersion: 2010-09-09

Description: DataBase for WordPress

Metadata:

    Authors:
        Description:  Fernando Brambilla de Mello

Parameters:

    MasterUsername:
        Type: String
    MasterUserPassword:
        Type: String
    DBInstanceId:
        Type: String
    DBName:
        Type: String
    Engine:
        Type: String
    DBInstanceClass:
        Type: String
    AllocatedStorage:
        Type: String    
    RDBSubnetGroup:
        Type: String 
    RDSSecurityGroup:
        Type: String

Resources:
 
    myRDS:
        Type: AWS::RDS::DBInstance
        Properties:
            DBInstanceIdentifier: !Ref DBInstanceId
            DBName: !Ref DBName
            DBInstanceClass: !Ref DBInstanceClass
            AllocatedStorage: !Ref AllocatedStorage
            Engine: !Ref Engine
            MasterUsername: !Ref   MasterUsername
            MasterUserPassword: !Ref MasterUserPassword
            DBSubnetGroupName: !Ref RDBSubnetGroup  
            VPCSecurityGroups:
               - !Ref RDSSecurityGroup

Outputs:
  DBInstanceIdentifier:
    Description: The database instance identifier
    Value: !Ref myRDS
    Export:
      Name: "DBInstanceIdentifier"

  DBEndpoint:
    Description: The connection endpoint for the database.
    Value: !GetAtt  myRDS.Endpoint.Address
    Export:
      Name: "DBEndpoint"

  DBPort:
    Description: The port number on which the database accepts connections.
    Value: !GetAtt  myRDS.Endpoint.Port
    Export:
      Name: "DBPort"     


