AWSTemplateFormatVersion: 2010-09-09

Description: DataBase for WordPress

Metadata:

    Authors:
        Description:  Fernando Brambilla de Mello

Parameters:
    myVpc:
        Type: String
    Subnet3:
        Type: String
    Subnet4:
        Type: String
    SshCidrAllow:
        Type: String   
    MasterUsername:
        Type: String
    MasterUserPassword:
        Type: String
    DBInstanceId:
        Type: String
    DBName:
        Type: String
    Engine:
        Type: String
    DBInstanceClass:
        Type: String
    AllocatedStorage:
        Type: String    

Resources:
    RDSSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupName: myRDS-SG
            GroupDescription: Frontend Access
            VpcId: 
                Ref: myVpc

    WebSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupName: myVPC-SG
            GroupDescription: Enable SSH, HTTP, HTTPS
            VpcId: 
                Ref: myVpc
            SecurityGroupIngress:
              - IpProtocol: tcp
                FromPort: '443'
                ToPort: '443'
                CidrIp: 0.0.0.0/0
              - IpProtocol: tcp
                FromPort: '22'
                ToPort: '22'
                CidrIp:
                    Ref: SshCidrAllow
              - IpProtocol: tcp
                FromPort: '80'
                ToPort: '80'
                CidrIp: 0.0.0.0/0    

    DBInboundRule:
        Type: AWS::EC2::SecurityGroupIngress
        Properties:
            IpProtocol: tcp
            FromPort: '3306'
            ToPort: '3306'
            SourceSecurityGroupId:
              Fn::GetAtt:
              - WebSecurityGroup
              - GroupId
            GroupId:
              Fn::GetAtt:
              - RDSSecurityGroup
              - GroupId

    myRDBSubnetGroup: 
        Type: "AWS::RDS::DBSubnetGroup"
        Properties: 
            DBSubnetGroupDescription: Create DB Subnet Group
            SubnetIds: 
              - Ref: Subnet4
              - Ref: Subnet3
            Tags:
              - Key: Name
                Value: SubGroup  
    myRDS:
        Type: 'AWS::RDS::DBInstance'
        Properties:
            DBInstanceIdentifier: !Ref DBInstanceId
            DBName: !Ref DBName
            DBInstanceClass: !Ref DBInstanceClass
            AllocatedStorage: !Ref AllocatedStorage
            Engine: !Ref Engine
            EngineVersion: 8.0.16
            MasterUsername: !Ref   MasterUsername
            MasterUserPassword: !Ref MasterUserPassword
            DBSubnetGroupName: !Ref myRDBSubnetGroup  
            VPCSecurityGroups:
               - !GetAtt RDSSecurityGroup.GroupId



Outputs:
  WebSecurityGroup:
    Description: EC2 Security Group
    Value: !Ref WebSecurityGroup
    Export:
      Name: "WebSecurityGroup"
      
  DBInstanceIdentifier:
    Description: The database instance identifier
    Value: !Ref myRDS
    Export:
      Name: "DBInstanceIdentifier"

  DBEndpoint:
    Description: The connection endpoint for the database.
    Value: !GetAtt  myRDS.Endpoint.Address
    Export:
      Name: "DBEndpoint"

  DBPort:
    Description: The port number on which the database accepts connections.
    Value: !GetAtt  myRDS.Endpoint.Port
    Export:
      Name: "DBPort"     




